application:
  mongodb:
    base-cluster:
      database: base
      username: base
      password: base1234!@
      primary:
        host: localhost
        port: 27017
      secondary:
        host: localhost
        port: 27018
spring:
  cloud:
    aws:
      sqs:
        email-send: email-send-queue-dev
        email-bounce: email-bounce-queue-dev
