server:
  port: 9900

spring:
  application:
    name: message-api
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  profiles:
    active: local
  cloud:
    aws:
      credentials:
        profile:
          name: default
      region:
        static: ap-northeast-2
# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, refresh
      base-path: /management